version: 1

# INTERMEDIATE DATA PRODUCTS CAN CONSUME A LOT OF STORAGE SPACE - BE WARNED
save-intermediate-products: False

# instrument the data belongs to; `xsh` or `soxs`
instrument: xsh
data-extension: 0

soxs-mbias:
    stacked-clipping-sigma: 5
    stacked-clipping-iterations: 5
    clipping-lower-sigma: 3
    clipping-upper-sigma: 3   
    clipping-iteration-count: 5

soxs-mdark:
    stacked-clipping-sigma: 5
    stacked-clipping-iterations: 5
    clipping-lower-sigma: 3
    clipping-upper-sigma: 3   
    clipping-iteration-count: 5

soxs-disp-solution:
    pixel-window-size: 10
    order-deg: 3
    wavelength-deg: 3
    # number of sigma-clipping iterations to perform before settings on a polynomial fit for the dispersion solution
    poly-clipping-iteration-limit: 10
    poly-fitting-residual-clipping-sigma: 5

soxs-order-centre:
    detect-continuum:
        # NUMBER OF CROSS-ORDER SLICES PER ORDER
        order-sample-count: 200
        # LENGTH OF EACH SLICE (PIXELS)
        slice-length: 10
        # HEIGHT GAUSSIAN PEAK MUST BE ABOVE MEDIAN FLUX TO BE "DETECTED" BY CODE (STD VIA MEDIAN ABSOLUTE DEVIATION).
        peak-sigma-limit: 1.5
        # DEGREE OF Y-COMPONENT OF GLOBAL POLYNOMIAL FIT TO ORDER CENTRES
        disp-axis-deg: 5
        # DEGREE OF ORDER-COMPONENT OF GLOBAL POLYNOMIAL FIT TO ORDER CENTRES
        order-deg: 6
        # CLIPPING LIMIT (MEDIAN AND MAD) WHEN FITTING GLOBAL POLYNOMIAL TO ORDER CENTRES
        poly-fitting-residual-clipping-sigma: 5
        # MAXIMUM NUMBER OF CLIPPING ITERATIONS WHEN FITTING GLOBAL POLYNOMIAL TO ORDER CENTRES
        poly-clipping-iteration-limit: 7

soxs-mflat:
    centre-order-window: 20
    stacked-clipping-sigma: 5
    stacked-clipping-iterations: 5
    clipping-lower-sigma: 50
    clipping-upper-sigma: 1000   
    clipping-iteration-count: 1
    slice-length-for-edge-detection: 90
    slice-width-for-edge-detection: 5
    min-percentage-threshold-for-edge-detection: 20
    max-percentage-threshold-for-edge-detection: 50
    disp-axis-deg: 2
    order-deg: 5
    poly-fitting-residual-clipping-sigma: 5
    poly-clipping-iteration-limit: 5
    low-sensitivity-clipping-sigma: 2

soxs-spatial-solution:
    pixel-window-size: 10
    order-deg: 4
    wavelength-deg: 5
    slit-deg: 2
    # number of sigma-clipping iterations to perform before settings on a polynomial fit for the dispersion solution
    poly-clipping-iteration-limit: 9
    poly-fitting-residual-clipping-sigma: 5
    map_to_image_displacement_threshold: 0.01 # in pixels


sky-subtraction:
    # MEDIAN CLIPPING FIRST USED TO CLIP MOST DEVIANT PIXELS (BAD AND CRHs)
    median_clipping_sigma: 3
    median_clipping_iterations: 5
    # ROLLING WINDOW LENGTH IN DATA POINTS
    median_rolling_window_size: 31
    # PECENTILE CLIPPING USED TO CLIP THE OBJECT(S) BEFORE FITTING A SKY MODEL
    percential_clipping_sigma: 2
    percential_clipping_iterations: 1
    percential_rolling_window_size: 15
    # FRACTION OF SLIT RANGE TO MASK AT UPPER AND LOWER SLIT EDGES
    clip-slit-edge-fraction: 0.05
    aggressive_object_masking: True
    bspline_order: 3
    slit_illumination_order: 3

soxs-stare:
    # number of σ deviations from the median *pixel* flux beyond which pixel is excluded from stack
    stacked-clipping-sigma: 5
    # number of σ-clipping iterations to perform before stacking
    stacked-clipping-iterations: 5
    # number of sigma-clipping iterations to perform when added pixels to the bad-pixel mask
    clipping-iteration-count: 1
     # number of σ below the median *frame* flux beyond which pixel is added to the bad-pixel mask
    clipping-lower-sigma: 50
    # number of sigma-clipping iterations to perform when added pixels to the bad-pixel mask
    clipping-upper-sigma: 1000 
    # the length of the 'slit' used to collect object flux (in pixels)
    horne-extraction-slit-length: 20
    # the number of σ deviations beyond the median pixel value for a pixel to be clipped (removing CRH and bad-pixels)
    horne-extraction-profile-global-clipping-sigma: 25
    # the number of σ deviations that residuals from the fitted, dispersion-direction profile need to be beyond for a pixel to be clipped
    horne-extraction-profile-clipping-sigma: 3.0
    # number of sigma-clipping iterations to perform while fitted, dispersion-direction profiles
    horne-extraction-profile-clipping-iteration-count: 10
    detect-continuum:
        # NUMBER OF CROSS-ORDER SLICES PER ORDER
        order-sample-count: 600
        # LENGTH OF EACH SLICE (PIXELS)
        slice-length: 10
        # HEIGHT GAUSSIAN PEAK MUST BE ABOVE MEDIAN FLUX TO BE "DETECTED" BY CODE (STD VIA MEDIAN ABSOLUTE DEVIATION).
        peak-sigma-limit: 1.5
        # DEGREE OF Y-COMPONENT OF GLOBAL POLYNOMIAL FIT TO OBJECT TRACE
        disp-axis-deg: 4
        # DEGREE OF ORDER-COMPONENT OF GLOBAL POLYNOMIAL FIT TO OBJECT TRACE
        order-deg: 4
        # CLIPPING LIMIT (MEDIAN AND MAD) WHEN FITTING GLOBAL POLYNOMIAL TO OBJECT TRACE
        poly-fitting-residual-clipping-sigma: 3.
        # MAXIMUM NUMBER OF CLIPPING ITERATIONS WHEN FITTING GLOBAL POLYNOMIAL TO OBJECT TRACE
        poly-clipping-iteration-limit: 5

# UTILS
background-subtraction:
    bspline-deg: 3
    median-filter-pixels: 9

logging settings:
    formatters:
        file_style:
            format: '%(asctime)s %(levelname)s: "%(pathname)s", line %(lineno)d, in %(funcName)s > %(message)s'
            datefmt: '%Y/%m/%d %H:%M:%S'
        console_style:
            format: '%(levelname)s: "%(pathname)s", line %(lineno)d, in %(funcName)s > %(message)s'
            datefmt: '%H:%M:%S'
        html_style:
            format: '<div id="row" class="%(levelname)s"><span class="date">%(asctime)s</span>   <span class="label">file:</span><span class="filename">%(filename)s</span>   <span class="label">method:</span><span class="funcName">%(funcName)s</span>   <span class="label">line#:</span><span class="lineno">%(lineno)d</span> <span class="pathname">%(pathname)s</span>  <div class="right"><span class="message">%(message)s</span><span class="levelname">%(levelname)s</span></div></div>'
            datefmt: '%Y-%m-%d <span class= "time">%H:%M <span class= "seconds">%Ss</span></span>'
    handlers:
        console:
            class: logging.StreamHandler
            level: WARNING
            formatter: console_style
            stream: ext://sys.stdout
        file:
            class: logging.handlers.GroupWriteRotatingFileHandler
            level: WARNING
            formatter: file_style
            filename: /Users/Dave/.config/soxspipe/soxspipe.log
            mode: w+
            maxBytes: 102400
            backupCount: 1
            delay: True
    root:
        level: INFO
        handlers: [file,console]

